### ISSUE TITLE
Bitcoin DevKit Wallet

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#169]
# Replace the bitcoind wallet with bdk wallet

- [x] Implement wallet traits using bdk
**We also used the electrum http API in addition to bdk as bdk did not have all the functionality we needed**
- [x] Create docker compose to start electrum and bitcoind 
- [x] Try using bitcoind as backend instead of electrum
**We could not get it working after a day so we gave up**
- [x] e2e tests passing using docker compose to start electrum and 

# Automate container start/shutdown so tests can run in CI

- [x] Decide whether to use test containers or docker compose
 **We decided to use test containers. Sharing volumes seems to be the only hurdle**

## Validate assumptions

Testing of these assumptions may not require an electrum testcontainer to be implemented. 

- [x] Validate assumption: Test containers allows volumes to be created/defined. 
- [x] Validate assumption: Test containers allows volumes to be shared. 
- [ ] Validate assumption: We can clean up volumes after the test has completed
- [ ] Validate assumption: We can use the GenericImage and do not need to create custom test containers

## Implement Test containers 
- [x] Spin up electrum using testcontainer and bitcoind using the working docker compose file. Tests passing .
- [x] Spin up electrum  and bitcoind using test containers. Tests passing.

# Cleanup tasks/ Potential problems
- [x] BDK wallet requires sync() to be called to update its internal database. It is not clear whether calls made from wallet.client() read the internal database or execute a rpc.
- [x] Architecture: Should we move sync() to seperate thread and call it in a loop?
- [ ] Extracting tx from the tx_lock psbt and then converting that extracted tx back into a psbt causes signing of the tx to fail with the bdk wallet. This issue was resolved by removing this conversion. This means that the psbt is sent from bob to Alice rather than the tx.
- [ ] Cleanup container code. The args should come from a struct. Cleanup/refactor the initialisattion code.
- [x] Generate the wallet descriptor from the seed
- [x] Update the config to use electrum instead of bitcoind

**Comment by luckysori** [comment]
> Extracting tx from the tx_lock psbt and then converting that extracted tx back into a psbt causes signing of the tx to fail with the bdk wallet. This issue was resolved by removing this conversion. This means that the psbt is sent from bob to Alice rather than the tx.

One thing to keep in mind is that AFAIK there is no strong reason for using PSBTs over regular transactions since `TxLock` is only ever signed by one party.

**Comment by thomaseizinger** [comment]
>     * BDK wallet requires sync() to be called to update its internal database. It is not clear whether calls made from wallet.client() read the internal database or execute a rpc.

It is my understanding that the client always just reads from the internal database.

**Comment by thomaseizinger** [comment]
> We can use the GenericImage and do not need to create custom test containers

This sounds like you are thinking that creating a custom image is a downside. It is not really. Implementing the trait is fairly straightforward and simplifies the call-site a lot because you can just make a new instance with `::default()`. You also don't necessarily need to contribute that image upstream, it can just be part of your codebase. See here: https://github.com/comit-network/xmr-btc-swap/blob/master/monero-harness/src/image.rs

> Validate assumption: We can clean up volumes after the test has completed

All volumes of a container will be deleted on shutdown: https://github.com/testcontainers/testcontainers-rs/blob/fe51e06fb2c44b1d3e3fd627cedea3fd582487ef/src/clients/cli.rs#L276

> Validate assumption: Test containers allows volumes to be shared.

Testcontainers doesn't care if you specify the same volume mapping for two containers. If what you want to do works with the docker CLI, it will work with testcontainers.

> Validate assumption: Test containers allows volumes to be created/defined.

Images can define volumes: https://github.com/testcontainers/testcontainers-rs/blob/fe51e06fb2c44b1d3e3fd627cedea3fd582487ef/src/core/image.rs#L84-L85

---

docker-compose and testcontainers don't play very well together conceptually. testcontainers is all about achieving test isolation, parallelization and automation where as docker-compose is about creating a more complex environment that can be manually started and stopped by the user.

**Comment by rishflab** [comment]
> > Extracting tx from the tx_lock psbt and then converting that extracted tx back into a psbt causes signing of the tx to fail with the bdk wallet. This issue was resolved by removing this conversion. This means that the psbt is sent from bob to Alice rather than the tx.
> 
> One thing to keep in mind is that AFAIK there is no strong reason for using PSBTs over regular transactions since `TxLock` is only ever signed by one party.

The sign API in bdk takes a PSBT unfortunately
