### ISSUE TITLE
Swap crate compiles very slowly

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#31]
Adding message1 is when compile times become slow. This is the comit where it becomes slow. Swap compiles fast before this commit.
[0f17ec076c09f064e62dd6ccac6d1c08f57b71a7](https://github.com/comit-network/xmr-btc-swap/commit/0f17ec076c09f064e62dd6ccac6d1c08f57b71a7)

This is the preceding commit that compiles fast
[5395303a99b0e66a5380e8d14ba48f573d6950fc](https://github.com/comit-network/xmr-btc-swap/commit/5395303a99b0e66a5380e8d14ba48f573d6950fc)

First commit with swap crate that compiles (fast): 
[hu04e1dca16afdb0834c8758ce0bc8eed3796812ec ](https://github.com/comit-network/xmr-btc-swap/commit/hu04e1dca16afdb0834c8758ce0bc8eed3796812ec )

**Comment by bonomat** [comment]
Removing `Descriptor` does not improve compile time: https://github.com/comit-network/xmr-btc-swap/pull/32

**Comment by bonomat** [comment]
Some more notes: 
We are very confident that the field `dleq_proof_s_b` and `dleq_proof_s_a` in `Message0` is the problem. 
https://github.com/comit-network/xmr-btc-swap/blob/713658244d5ec27f5763a4b74403d7dabf09db90/xmr-btc/src/bob/message.rs#L20

Removing this field makes the compilation "faster" but not yet blazing fast. 
Derived from this, we think that the actual problem is the library `GenericArrays` in our dleq-proof library. See this PR for updates: https://github.com/comit-network/cross-curve-dleq/pull/6

**Comment by thomaseizinger** [comment]
Have you tried using optimizations like using [a different linker or a nightly compiler](https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional)?
