### ISSUE TITLE
cargo attempts to compile tokio-tar on windows and fails

### ISSUE THREAD

**Issue by rishflab** [comit-network/xmr-btc-swap#315]
```
Compiling tokio-tar v0.2.0 (...\xmr-btc-swap\tokio-tar)
   Compiling curve25519-dalek v3.0.2
   Compiling sha2 v0.9.2
error[E0433]: failed to resolve: could not find `os` in `fs`
error[E0433]: failed to resolve: could not find `os` in `fs`
   --> tokio-tar\src\entry.rs:583:28
    |
583 |                 tokio::fs::os::windows::symlink_file(src, dst).await
    |                            ^^ could not find `os` in `fs`

```

It seems to trying to compile the tokio-tar git submodule.

When this merges we can https://github.com/vorot93/tokio-tar/pull/3 it should no longer be an issue

**Comment by thomaseizinger** [comment]
There is two ways we can solve this:

1. Close this in favor of https://github.com/comit-network/xmr-btc-swap/issues/227.
2. Make the code compile on Windows.

For (2), a quick-fix could be to simply provide alternative implementations that panic at runtime because we are never using this on Windows.
