### ISSUE TITLE
Give asb operators the ability to reuse an existing Monero wallet

### ISSUE THREAD

**Issue by c22** [comit-network/xmr-btc-swap#352]
Currently if you run asb, it creates the XMR wallet for you.

Operators should have the ability to specify a wallet that already exists.

**Comment by da-kami** [comment]
After giving this feature some thought we decided against implementing this, because it would add security assumptions for existing user wallets. 

Right now, we create a wallet that is to be funded with Monero. The ASB only has control over that wallet, which does not have a password (and hence no password is stored). 
We have to start the monero wallet rpc with `--wallet-dir` because when Alice refunds she must be able to claim the XMR refunded using `generate_from_keys` (which creates a new wallet to claim the XMR - that wallet is drained and the default wallet is reloaded). In order to be able to re-load the wallet we have to store the `password`, which is not easily done in a secure way:

- We cannot use the `--password-file` because it does not work properly in combination with the `--wallet-dir` option as recorded here: https://github.com/monero-project/monero/issues/7624
- Saving the wallet's password in the config file is not a secure option, as config files are usually not kept securely.
- Eventually we could opt for specifying the password in an environment variable, but that adds some complexity to the initial setup and error scenarios.

To keep the solution simple and don't add security assumptions, we thus decided to keep the default wallet `asb-wallet` and don't allow user wallets for now.

**Comment by c22** [comment]
Thanks Daniel. As I understand it, you have abandoned #369 as an implementation of this feature, but are not opposed to supporting this feature in the future?

**Comment by da-kami** [comment]
> Thanks Daniel. As I understand it, you have abandoned #369 as an implementation of this feature, but are not opposed to supporting this feature in the future?

For the moment we are not planning to support using a user wallet because there are too many security assumptions around it.
We believe that it is reasonable for a service provider to send Monero to the wallet intitially.

We are planning to tighten security around the created `asb-wallet` by:

- RPC username + password through login file #349 
- `asb-wallet` password derived from the asb seed to tighten security #382
