### ISSUE TITLE
Database that allows migrations

### ISSUE THREAD

**Issue by da-kami** [comit-network/xmr-btc-swap#427]
The currently `swap` and `asb` implementations use a [`sled`](https://docs.rs/sled/0.34.6/sled/) database for storing the swap state. This is not optimal, because sled does not allow migrations. 
This can result in a loss of information between version. Notably that happened between version `v0.3` and `0.4.0` because we introduced different trees to store the information in sled. When running the history command in `0.4.0` (and above) older swaps are just not shown. 

We opted for sled initially to ramp up the prototype fast, but now that we have releases and are moving towards mainnet it would be better to have a database that allows proper migrations, so we can always properly access all previous swaps in the database. 

One solution is to use [`diesel`](https://docs.rs/diesel/1.4.6/diesel/) instead of sled. This is a major refactoring, because the overall structure of the database would most likely change (i.e. save the data in multiple relational tables rather than just one big state chunk).

**Comment by thomaseizinger** [comment]
Two nits:

1. Nothing in sled prevents migrations, we would just have to roll them ourselves.
2. `diesel` is an ORM and `sled` is the database. Most likely, you wanted to point to `sqlite` instead of `diesel` as there are also [other](https://github.com/launchbadge/sqlx) ways of using SQL from within Rust.

**Comment by thomaseizinger** [comment]
## Mentoring notes for migrating to sqlite

1. The very first step is to make the database layer actually independent. In particular [these](https://github.com/comit-network/xmr-btc-swap/blob/6ec5e34f8043df36aa9e7065c846cb382875f8e0/swap/src/database.rs#L195-L262) functions should use the domain objects that are used throughout the rest of the codebase. Once that is done, we can mess around with the database layer without affecting the rest of the code.
2. Pick a Rust SQL library. We've used `diesel` in the past but it can get a bit verbose. Not sure if `sqlx` is any better, at least it would be natively async. For that reason, I would prefer if we can make `sqlx` work.
3. Our database currently has [four trees](https://github.com/comit-network/xmr-btc-swap/blob/6ec5e34f8043df36aa9e7065c846cb382875f8e0/swap/src/database.rs#L69-L72): `swaps`, `peers`, `addresses` and `monero_addresses`. The latter three translate nicely into tables of a relational schema. To start with, I would pick one of those and try storing it in sqlite instead of sled. This should yield us most of the infrastructure we need for the other trees, in particular it should include **migrations** that track the changes to the SQL schema and are automatically applied on startup of the application.

(1) can be an independent patch that we can either merge directly or have as the leading patch at the front of a PR.
(3) is again something that we can merge independently or build as a 2nd patch on top of (1).

4. Repeat (3) with the other two trees, i.e. everything apart from `swaps`.
5. `swaps` will be a bit trickier because it gets updated throughout the execution. My proposal would be that we have a table that looks something like this:

| id | swap_id | state | inserted_at |
| --- | --- | --- | --- |
| unique_id | swap_id | state serialized as JSON | insertion timestamp |

Instead of updating the state as we do now, we just insert a new row into this table when [`insert_latest_state`](https://github.com/comit-network/xmr-btc-swap/blob/6ec5e34f8043df36aa9e7065c846cb382875f8e0/swap/src/database.rs#L195-L211) gets called. When [loading a swap](https://github.com/comit-network/xmr-btc-swap/blob/6ec5e34f8043df36aa9e7065c846cb382875f8e0/swap/src/database.rs#L213-L223), we just find the latest timestamp and load the JSON and deserialize it.

Doing all of this should allow us to get rid of `sled` and have everything in sqlite. To actually make use of the relational schema, we will have to update the rest of the application save more fine-granular state. That is a bigger effort on its own that we can talk about once all of this is done!

**Comment by rishflab** [comment]
Plan for smooth migrating users from sled to sqlite

Release a build that supports both sled and sqlite:

1. If the user does not have an existing sled db it will create a sqlite db and run as if sled never existed.
2. If the user has an existing sled db, it will load all the swap states from the DB and then save them to sqlite and print a message informing the user what has happened.
 - I am not sure whether this should be automatic or triggered by a subcommand
 - The write to the sqlite db should be atomic. This may require changing/creating an insert function to take an `Iter instead of single `swap`

**Comment by thomaseizinger** [comment]
Sounds good!

I wouldn't worry too much about the atomicity. In case something fails, the user can always delete the sqlite file and run the tool again. Once the migration worked, they can delete the sled DB.
