### ISSUE TITLE
Mainnet-ready feees for Monero

### ISSUE THREAD

**Issue by bonomat** [comit-network/xmr-btc-swap#470]
Follow-up issue from #443 .

Come up with a reasonable fee or a way to dynamically compute fees for Monero.

**Comment by da-kami** [comment]
Maybe I am missing something, but I don't think there is anything to do for this ticket.

On Monero there are three transactions that are relevant:

1. The lock transaction (Alice)
2. Spending the XMR from the generated wallet when redeeming (Bob)
3. Spending the XMR from the generated wallet when refunding (Alice)

None of these transactions require any agreement on fees between the parties.

We use [`transfer`](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#transfer) for all of the transactions above.
As far as I could see, there is no `fee` field that can set when triggering a transfer. The fee will automatically be estimated by the `monero-wallet-rpc`(and I assume that fee is ultimately coming from the monero node the RPC is connected to).

**Comment by da-kami** [comment]
Short correction for completion:

the `monoer-wallet-rpc` [`transfer`](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#transfer) offers the concept of `priority` which acts as a multiplier on transaction fee.

```
priority - unsigned int; Set a priority for the transaction. Accepted Values are: 0-3 for: default, unimportant, normal, elevated, priority.
```

Default priority (priority `0`) effectively means priority `2` which corresponds to a factor of `x4`. 

See:
https://monero.stackexchange.com/questions/4544/what-does-the-default-priority-priority-0-do-in-monero-wallet-cli

https://github.com/da-kami/monero/blob/2098941ca03b7aa1f92bfa802d2600c075d4bd70/src/wallet/wallet2.cpp#L7478-L7518

Eventually we could allow adjusting priority to `1`, because the protocol does not have a need for the Monero transactions to be included especially fast.
Default priority is acceptable for now.
