### ISSUE TITLE
We sometimes hit `InsufficientFunds` when funding Bitcoin LockTx

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#546]
I think this happens because we use random keys to predict the weight of `TxLock`. Instead, we should probably hardocde a meaningful weight of `TxLock` and always use that when calculating [`max_giveable`](https://github.com/comit-network/xmr-btc-swap/blob/d5d0dda6e73c76911edcae513a0333ca11a35330/swap/src/bin/swap.rs#L102).

**Comment by bonomat** [comment]
We had this error when estimating `max_giveable`. 
`InsufficientFunds` is an error thrown by the BDK-wallet when creating a transaction using the transaction builder. We included a fix for this here: 

https://github.com/comit-network/xmr-btc-swap/blob/eb705d3e9c85938ce7d2c990ea8daab9569eeda1/swap/src/bitcoin/wallet.rs#L369-L375

We have a [second place using this builder](https://github.com/comit-network/xmr-btc-swap/blob/eb705d3e9c85938ce7d2c990ea8daab9569eeda1/swap/src/bitcoin/wallet.rs#L315) but it _should not happen_ there because we compute the max giveable amount beforehand. :) 
Interesting though...

Do you know what version this was recorded?
