### ISSUE TITLE
Swap failed while Waiting for Alice to lock Monero

### ISSUE THREAD

**Issue by MONT3M** [comit-network/xmr-btc-swap#688]
Hi All, 

I initiated a swap for 0.03 BTC (with the funds already in the internal wallet of the swap tool from a previously cancelled swap) and it failed as shown in the code at the bottom of this post. 

The terminal was stuck on "Waiting for Alice to lock Monero" for a few hours before I went to sleep. Upon waking in the morning, I saw that the swap had failed/been cancelled as "Alice took too long to lock Monero."  The ASB had punished me and took the 0.03 BTC sometime during the night as well. Afaik there was not break in my internet connection during this time. 

Fortunately, I was contacted by the ASB operator that I initiated the swap with, and they were kind enough to let me know that there was no malicious intent behind the automatic punish and would like to see me get the XMR funds. 

However they are also at a loss as to how I can recover my XMR funds as this situation has not happened to them before. According to them, the XMR are locked in the swap tool and need to be somehow be manually released to my XMR wallet. Would this manual release be accomplished from the trader or ASB side? Thank you for any help you can provide to either of us. 

Terminal:
```
`XXXX@XXXX:~/Downloads$ ./swap buy-xmr --receive-address 4A8T1raSjhZf4WFAa3fBSxSLCF4PKk1ZEAXB28EcP7Z7QTdz8WYPLz3Ak2TF1bqBgMgCF8zZZpFDn8sFnVn6YpxoNkgXTA4 --change-address bc1qe43v6xas2uf3j7wq97w7jkckkk98hvlhs00u4r --seller /dnsaddr/commitcri.me/p2p/12D3KooWNT2FCb52QmQS1E4zGzaGdAkGWMUcBJuqTUTrkW3drvuf
Connected to Alice at /dnsaddr/commitcri.me/p2p/12D3KooWNT2FCb52QmQS1E4zGzaGdAkGWMUcBJuqTUTrkW3drvuf
Received quote price=0.00668673 BTC minimum_amount=0.00010000 BTC maximum_amount=0.03000000 BTC
Starting new swap amount=0.02999741 BTC fees=0.00000259 BTC swap_id=19b5438a-44ab-4fb8-9525-932e6d41f6dc
Estimated fee of 289.3440 is smaller than the min relay fee, defaulting to min relay fee 1000
Estimated fee of 314.6880 is smaller than the min relay fee, defaulting to min relay fee 1000
Published Bitcoin transaction txid=cc785b2ab2f1d546500c9d4040d5e634abfd6ee18188e12ffbac264111e79dac kind=lock
Waiting for Alice to lock Monero
Failed to get status of script: Failed to subscribe to header notifications: Made one or multiple attempts, all errored:
- CloseNotify alert received
txid=cc785b2ab2f1d546500c9d4040d5e634abfd6ee18188e12ffbac264111e79dac
Alice took too long to lock Monero, cancelling the swap
Error: Failed to complete swap

Caused by:
0: Failed to broadcast Bitcoin cancel transaction 50e4ea7e3b3d27a761f1be47cb207f958d2e4e10b36f694cd9c6629d239cd14e
1: Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))`
```

**Comment by thomaseizinger** [comment]
> And in a future where a manual release may be possible, what if Alice doesn't contact Bob or want to cooperatively release the locked XMR funds? Is Bob doomed to lose the BTC after the ASB automatically punishes after the 72 block timeframe?

Yes, this is due to Monero not having any timelocks. From the protocol perspective, Bob (the user) may be malicious and never claim the XMR. Without claiming the XMR, Alice can never retrieve the BTC.

As a result, she is allowed to claim the BTC funds after another 72 block time window.

Swap protocols are time-sensitive. As long as both parties are online and act within a certain time frame, no funds are lost. If one party just disappears either willingly or unwillingly, certain spending paths must become possible otherwise the incentives in the protocol don't work out. That is unfortunately the nature of non-custodial and trustless protocols like these.

> will sit in the swap tool address for the rest of time?

They don't sit in the tool. They sit in a multi-sig on the chain and can only be claimed through collaboration by both parties. Normal execution of the swap is essentially this collaboration.

> I am surprised that there is no current way for Bob to retrieve the locked XMR after Alice has punished and retrieved the BTC. May I ask why this is not standard to the protocol?

It may be possible but has to be thought through properly, I've opened a discussion here: https://github.com/comit-network/xmr-btc-swap/discussions/713

**Comment by rishflab** [comment]
Addressed in linked PR
