### ISSUE TITLE
Swap failed at the very end - Update: Funds were lost

### ISSUE THREAD

**Issue by TA1002** [comit-network/xmr-btc-swap#695]
I wasn't sure how to phrase the title of this. The swap seemed to just "hang" right before I would typically see "Successfully transferred XMR to wallet...". I'm using the "preview" version of swap.

Relevant logs below:

Waiting for Alice to lock Monero
Alice locked Monero txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25
Waiting for Monero transaction finality txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 target_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=1 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=2 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=3 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=4 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=5 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=6 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=7 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=8 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=9 needed_confirmations=10
Received new confirmation for Monero lock tx txid=85847cd1a959e2db715dcf981fbe8d223d85e3123ee9d9fa4356421514ff2b25 seen_confirmations=11 needed_confirmations=10

And then it stuck here for over an hour. So I exited and tried resuming, canceling, or refunding, even 12+ hours later. For a while the state was "encrypted signature sent", and is now "cancel timelock expired". Note the "seen_confirmations" went from 9 to 11. I've seen this a few times, even when the swap succeeds. I have not seen the Monero appear in my wallet. 

There seems to be a reoccurring issue I see every time when a swap fails. It seems to automatically try to refund the BTC without any manual intervention, but fails *every* time. 

Here are the current responses I get for resume, refund, or cancel:

swap resume --swap-id 3d3aed46-ad4f-4605-a38f-6e7adf4ac56c 
Connected to Alice at /ip4/51.15.44.142/tcp/9939/p2p/12D3KooWAPci3x4GuWDi9P86efnR1q9a7phKnPwnwQcRNMW2HDUy
Error: Failed to broadcast Bitcoin cancel transaction 7f218ab47a0b2f785aa9d63d89ebe558d14e14ef500f08a1943fdbc2b904aa0f

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-25,\"message\":\"bad-txns-inputs-missingorspent\"}")))

swap refund --swap-id 3d3aed46-ad4f-4605-a38f-6e7adf4ac56c 
Error: Cannot refund because swap 3d3aed46-ad4f-4605-a38f-6e7adf4ac56c was not cancelled yet. Make sure to cancel the swap before trying to refund.

swap cancel --swap-id 3d3aed46-ad4f-4605-a38f-6e7adf4ac56c 
Manually cancelling swap swap_id=3d3aed46-ad4f-4605-a38f-6e7adf4ac56c
The cancel transaction cannot be published yet, because the timelock has not expired. Please try again later

The "bad-txns-inputs-missingorspent" doesn't bode well for trying to recover the BTC. Hopefully I'm wrong.

**Comment by jgreth0** [comment]
Was there ever a resolution to this? I just ran into the same issue. Jumped from 9 to 12 confirmations, then hang.

**Comment by jgreth0** [comment]
Update: I force quit and tried the following:
> .\swap history
+--------------------------------------+-----------------+
| SWAP ID                              | STATE           |
+========================================================+
| <xxxx> | btc is redeemed |
+--------------------------------------+-----------------+

> .\swap resume --swap-id <xxxx>
Failed to generate monero wallet from keys: Failed to generate new wallet from keys: JSON-RPC request failed with code -1: Wallet already exists.: JSON-RPC request failed with code -1: Wallet already exists.
Falling back to trying to open the the wallet if it already exists wallet_file_name=<xxxx>
Connected to Alice at /ip4/51.15.44.142/tcp/9939/p2p/<yyyy>
Error: JSON-RPC request failed with code -1: Failed to open wallet

Caused by:
    JSON-RPC request failed with code -1: Failed to open wallet


Is there any documentation on the state machine, or any hope I can manually complete the transaction if this is a bug? I assume "btc is redeemed" means that Alice has claimed the bitcoin, thus exposing the key which should allow me to access the xmr if I can figure out how. I saved the shell history so I have a record of all the relevant transactions IDs.
