### ISSUE TITLE
Failed Swap, did not get refund. Transaction not in Database.

### ISSUE THREAD

**Issue by scootercommuter** [comit-network/xmr-btc-swap#789]
My swap failed, and I did not receive a refund.  My funds are lost.  I have had 2 previous successful swaps.  I have lost over $400.  Any help on this?

Error message:
Error: Failed to complete swap
Caused by:
  0: Failed to seserialize bytes into message using CBOR
  1: EOF while parsing a value
![FailedSwap20210921](https://user-images.githubusercontent.com/13461722/134258098-656636e4-c679-4172-9a6d-48442f4164b0.JPG)
![BTC_Sent_20210921](https://user-images.githubusercontent.com/13461722/134258120-2130af62-b691-4c4e-a0ae-34c8ef029ea4.JPG)

![BlockExplorer_20210921](https://user-images.githubusercontent.com/13461722/134258128-4056bcc1-ebb2-4a10-8ae8-93b0b7393ef7.JPG)

**Comment by scootercommuter** [comment]
Refund failed.  "Swap with id (correct number) not found in database"  Please Help Me
![RefundFailed_20210921](https://user-images.githubusercontent.com/13461722/134259321-7cb65cd2-cfa4-446f-80b7-52b7f1c91b44.JPG)
!

**Comment by xrv0** [comment]
Can you try running ```
./swap balance
```?

**Comment by GordianSimpul** [comment]
This same error occurred two weeks ago. The OP was got their bitcoin back.

See issue:  https://github.com/comit-network/xmr-btc-swap/issues/729

There is a post on reddit that explains how you **should** be able to get your BTC back. Apparently this is caused when the provider does not have enough XMR in their wallet and the CLI quits on you instead of acknowledging insufficient funds and refunding your Bitcoin. 

See: https://www.reddit.com/r/Monero/comments/pi2v86/atomic_swap_problem_sellers_xmr_balance_is/

If you are not on the swap CLI 0.8.3. I suggest downloading it. There is an option to withdraw your bitcoin

`./swap withdraw-btc --address your_btc_address`

Hope that helps and you get your monies back.

**Comment by GordianSimpul** [comment]
NOTE: to be safe, use the btc address you sent the funds to in the above command. I doubt that it matters, but it would be on the safe side to do that. 

Also, my suggestion is not to swap the maximum amount provided by the provider. I conducted a swap a week ago and picked somewhere in the middle and it was successful. Users need to take precautions with new software, it won't always work as intended until it matures. 

Also, also, always use the most recent version of the software. Bugs are still being worked out and users should have less problems with newer versions.

**Comment by GordianSimpul** [comment]
btc address you sent the fund **FROM**

**Comment by scootercommuter** [comment]
> 
> 
> Can you try running `./swap balance`?

PS C:\Users\kevin\Desktop> ./swap balance
Bitcoin balance is 0.01000000 BTC
